# Costanti fisiche e parametri ESWT
"""
Costanti fisiche fondamentali e parametri tipici per dispositivi ESWT.

Questo modulo contiene:
    - PhysicalConstants: Costanti fisiche universali
    - ESWTParameters: Parametri tipici per dispositivi ESWT elettroidraulici
    - AcousticImpedance: Impedenze acustiche dei tessuti (da Ogden 2001)

Riferimenti:
    - Ogden et al. (2001) "Principles of Shock Wave Therapy"
    - Chen et al. (2010) "Experimental and numerical study of shock wave
      propagation in water generated by PAED"
    - Slezak et al. (2022) "Physical Considerations for In Vitro ESWT Research Design"
"""

from dataclasses import dataclass
from .units import ureg, Q_


@dataclass(frozen=True)
class PhysicalConstants:
    """
    Costanti fisiche universali usate nel simulatore.

    Tutte le grandezze sono espresse con unità Pint per garantire
    consistenza dimensionale nei calcoli.
    """

    # Velocità del suono in acqua a 25°C (m/s)
    VELOCITA_SUONO_ACQUA = Q_(1492, "m/s")

    # Densità acqua a 25°C (kg/m³)
    DENSITA_ACQUA = Q_(998.3, "kg/m^3")

    # Calore specifico acqua (J/(kg·K))
    CALORE_SPECIFICO_ACQUA = Q_(4186, "J/(kg*K)")

    # Pressione atmosferica (Pa)
    PRESSIONE_ATMOSFERICA = Q_(101325, "Pa")

    # Temperatura ambiente (°C)
    TEMPERATURA_AMBIENTE = Q_(25, "degC")

    # Costante dei gas ideali (J/(mol·K))
    R_GAS = Q_(8.314, "J/(mol*K)")

    # Temperatura di vaporizzazione acqua a 1 atm (°C)
    TEMPERATURA_VAPORIZZAZIONE = Q_(100, "degC")

    # Entalpia di vaporizzazione acqua (J/kg)
    ENTALPIA_VAPORIZZAZIONE = Q_(2.26e6, "J/kg")


@dataclass(frozen=True)
class ESWTParameters:
    """
    Parametri tipici per dispositivi ESWT elettroidraulici.

    Valori derivati dalla letteratura scientifica (Ogden 2001, Chen 2010).
    """

    # Range tensione condensatore (kV)
    TENSIONE_MIN = Q_(10, "kV")
    TENSIONE_MAX = Q_(30, "kV")

    # Range capacità (μF)
    CAPACITA_MIN = Q_(0.1, "uF")
    CAPACITA_MAX = Q_(10, "uF")

    # Range induttanza circuito (μH)
    INDUTTANZA_MIN = Q_(1, "uH")
    INDUTTANZA_MAX = Q_(10, "uH")

    # Range energia per impulso (J) - da Chen 2010
    ENERGIA_MIN = Q_(20, "J")
    ENERGIA_MAX = Q_(3300, "J")

    # Durata tipica scarica (μs)
    DURATA_SCARICA_TIPICA = Q_(1, "us")
    DURATA_SCARICA_MAX = Q_(10, "us")

    # Pressione picco tipica (MPa) - da Ogden 2001
    PRESSIONE_PICCO_MIN = Q_(40, "MPa")
    PRESSIONE_PICCO_MAX = Q_(100, "MPa")

    # Rise time onda d'urto (ns)
    RISE_TIME = Q_(10, "ns")

    # Energy flux density (mJ/mm²) - da Ogden 2001 Table 1
    EFD_LOW = Q_(0.09, "mJ/mm^2")
    EFD_MEDIUM = Q_(0.24, "mJ/mm^2")
    EFD_HIGH = Q_(0.40, "mJ/mm^2")

    # Distanza inter-elettrodo tipica (mm)
    GAP_ELETTRODI_MIN = Q_(5, "mm")
    GAP_ELETTRODI_MAX = Q_(10, "mm")

    # Frequenza di ripetizione impulsi (Hz)
    FREQUENZA_IMPULSI_TIPICA = Q_(3, "Hz")


@dataclass(frozen=True)
class AcousticImpedance:
    """
    Impedenze acustiche dei materiali/tessuti.

    Dati da Ogden et al. (2001) Table 3.
    Z = ρ × c (densità × velocità del suono)
    Unità: g/(cm²·s) × 10⁵ = 10⁵ kg/(m²·s) = 10⁵ Rayl
    """

    # Acqua
    ACQUA_DENSITA = Q_(1.0, "g/cm^3")
    ACQUA_VELOCITA = Q_(1492, "m/s")
    ACQUA_IMPEDENZA = Q_(1.49e5, "kg/(m^2*s)")

    # Muscolo
    MUSCOLO_DENSITA = Q_(1.06, "g/cm^3")
    MUSCOLO_VELOCITA = Q_(1630, "m/s")
    MUSCOLO_IMPEDENZA = Q_(1.72e5, "kg/(m^2*s)")

    # Grasso
    GRASSO_DENSITA = Q_(0.9, "g/cm^3")
    GRASSO_VELOCITA = Q_(1476, "m/s")
    GRASSO_IMPEDENZA = Q_(1.37e5, "kg/(m^2*s)")

    # Osso corticale
    OSSO_CORTICALE_DENSITA = Q_(1.8, "g/cm^3")
    OSSO_CORTICALE_VELOCITA = Q_(4100, "m/s")
    OSSO_CORTICALE_IMPEDENZA = Q_(7.38e5, "kg/(m^2*s)")

    # Osso spongioso
    OSSO_SPONGIOSO_DENSITA = Q_(1.0, "g/cm^3")
    OSSO_SPONGIOSO_VELOCITA = Q_(1450, "m/s")
    OSSO_SPONGIOSO_IMPEDENZA = Q_(1.45e5, "kg/(m^2*s)")


@dataclass(frozen=True)
class ElectrodeProperties:
    """
    Proprietà dei materiali per elettrodi tipici in dispositivi ESWT.
    """

    # Tungsteno (comune per elettrodi ESWT)
    TUNGSTENO_DENSITA = Q_(19300, "kg/m^3")
    TUNGSTENO_PUNTO_FUSIONE = Q_(3422, "degC")
    TUNGSTENO_CONDUCIBILITA_TERMICA = Q_(173, "W/(m*K)")

    # Rame (alternativa)
    RAME_DENSITA = Q_(8960, "kg/m^3")
    RAME_PUNTO_FUSIONE = Q_(1085, "degC")
    RAME_CONDUCIBILITA_TERMICA = Q_(401, "W/(m*K)")

    # Acciaio inox (usato in alcuni setup - da Chen 2010)
    ACCIAIO_DENSITA = Q_(8000, "kg/m^3")


@dataclass(frozen=True)
class ChenModelParameters:
    """
    Parametri specifici per il modello Chen et al. (2010).

    Questi parametri sono stati validati sperimentalmente con errori
    relativi del 3.6-7.8%.
    """

    # Frazione energia per riscaldamento acqua (prima del breakdown)
    FRAZIONE_ENERGIA_RISCALDAMENTO = 0.10  # 10%

    # Frazione energia per generazione onda d'urto
    FRAZIONE_ENERGIA_SHOCKWAVE = 0.90  # 90%

    # Temperatura target per vaporizzazione (°C)
    TEMPERATURA_VAPORIZZAZIONE_TARGET = Q_(95, "degC")

    # Coefficiente smorzamento ridotto (per simulazione FEM)
    SMORZAMENTO_RIDOTTO = 0.005

    # Costante smorzamento quadratico
    SMORZAMENTO_QUADRATICO_MIN = 8
    SMORZAMENTO_QUADRATICO_MAX = 12


def calcola_impedenza_acustica(densita: "Q_", velocita_suono: "Q_") -> "Q_":
    """
    Calcola l'impedenza acustica di un materiale.

    Z = ρ × c

    Parametri:
        densita: Densità del materiale (kg/m³)
        velocita_suono: Velocità del suono nel materiale (m/s)

    Ritorna:
        Impedenza acustica (kg/(m²·s) = Rayl)
    """
    return densita * velocita_suono


def coefficiente_riflessione(z1: "Q_", z2: "Q_") -> float:
    """
    Calcola il coefficiente di riflessione all'interfaccia tra due mezzi.

    R = ((Z2 - Z1) / (Z2 + Z1))²

    Da Ogden et al. (2001).

    Parametri:
        z1: Impedenza acustica mezzo 1
        z2: Impedenza acustica mezzo 2

    Ritorna:
        Coefficiente di riflessione (0-1, adimensionale)
    """
    z1_val = z1.to("kg/(m^2*s)").magnitude
    z2_val = z2.to("kg/(m^2*s)").magnitude
    return ((z2_val - z1_val) / (z2_val + z1_val)) ** 2


def coefficiente_trasmissione(z1: "Q_", z2: "Q_") -> float:
    """
    Calcola il coefficiente di trasmissione all'interfaccia tra due mezzi.

    T = 4·Z1·Z2 / (Z1 + Z2)²

    Da Ogden et al. (2001).

    Parametri:
        z1: Impedenza acustica mezzo 1
        z2: Impedenza acustica mezzo 2

    Ritorna:
        Coefficiente di trasmissione (0-1, adimensionale)
    """
    z1_val = z1.to("kg/(m^2*s)").magnitude
    z2_val = z2.to("kg/(m^2*s)").magnitude
    return 4 * z1_val * z2_val / (z1_val + z2_val) ** 2
